import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'studentPortalLanguage';

const translations = {
    hi: {
        'Language': 'भाषा',
        'English': 'English',
        'Hindi': 'हिंदी',
        'Switch language': 'भाषा बदलें',
        'Institute': 'स्टूडेंट पोर्टल',
        'Roll': 'रोल',
        'MAIN': 'मुख्य',
        'ACADEMICS': 'शैक्षणिक',
        'INFO': 'जानकारी',
        'Dashboard': 'डैशबोर्ड',
        'Settings': 'सेटिंग्स',
        'My Profile': 'मेरी प्रोफाइल',
        'Subjects': 'विषय',
        'Attendance': 'उपस्थिति',
        'Results': 'परिणाम',
        'Leaderboard': 'लीडरबोर्ड',
        'Fees': 'फीस',
        'Contact & Support': 'संपर्क और सहायता',
        'Home': 'होम',
        'Attend': 'अटेंड',
        'Logout': 'लॉगआउट',
        'Profile': 'प्रोफाइल',
        'My Subjects': 'मेरे विषय',
        'My Results': 'मेरे परिणाम',
        'My Fees': 'मेरी फीस',
        'Attendance Detail': 'उपस्थिति विवरण',
        'Hall of Fame': 'टॉप रैंकिंग',
        'Student Access': 'स्टूडेंट एक्सेस',
        'Secure login for students only.': 'केवल छात्रों के लिए सुरक्षित लॉगिन।',
        'Student ID': 'स्टूडेंट आईडी',
        'Password': 'पासवर्ड',
        'Roll number or email is required.': 'रोल नंबर या ईमेल जरूरी है।',
        'Password is required.': 'पासवर्ड जरूरी है।',
        'Invalid roll number or password. Please try again.': 'गलत रोल नंबर या पासवर्ड। फिर से कोशिश करें।',
        'Too many attempts. Please wait a minute and try again.': 'बहुत अधिक प्रयास हुए हैं। एक मिनट बाद फिर कोशिश करें।',
        'Unable to reach the server. Check your internet connection.': 'सर्वर तक पहुंच नहीं हो सकी। अपना इंटरनेट कनेक्शन जांचें।',
        'Login failed. Please try again.': 'लॉगिन असफल रहा। फिर से कोशिश करें।',
        'Enter your password': 'अपना पासवर्ड दर्ज करें',
        'Show password': 'पासवर्ड दिखाएं',
        'Hide password': 'पासवर्ड छिपाएं',
        'Signing In...': 'साइन इन हो रहा है...',
        'Secure Login Access': 'सुरक्षित लॉगिन',
        'Security Activation': 'सुरक्षा सक्रियण',
        'Setup Portal': 'पोर्टल सेटअप',
        'Verify your identity and secure your workspace.': 'अपनी पहचान सत्यापित करें और अपना पोर्टल सुरक्षित करें।',
        'Image size must be less than 2MB': 'इमेज साइज 2MB से कम होना चाहिए',
        'Please upload a profile picture': 'कृपया प्रोफाइल फोटो अपलोड करें',
        'Password must be at least 6 characters long': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
        'Passwords do not match': 'पासवर्ड मेल नहीं खा रहे हैं',
        'Failed to complete setup': 'सेटअप पूरा नहीं हो सका',
        'Professional Photo': 'प्रोफेशनल फोटो',
        'Upload a clear front-facing photo. This will be used for your official ID card and cannot be changed.': 'सामने से साफ फोटो अपलोड करें। यह आपकी आधिकारिक आईडी कार्ड के लिए उपयोग होगी और बाद में बदली नहीं जा सकेगी।',
        'Secure My Account': 'मेरा अकाउंट सुरक्षित करें',
        'Please upload your photo to continue': 'जारी रखने के लिए अपनी फोटो अपलोड करें',
        'Set New Password': 'नया पासवर्ड सेट करें',
        'Choose a strong password': 'मजबूत पासवर्ड चुनें',
        'Confirm Identity': 'पहचान की पुष्टि करें',
        'Repeat the password': 'पासवर्ड दोबारा लिखें',
        'Go Back': 'वापस जाएं',
        'Processing...': 'प्रोसेस हो रहा है...',
        'Activate Portal': 'पोर्टल सक्रिय करें',
        'Identity Verified': 'पहचान सत्यापित',
        'Entry Granted': 'प्रवेश स्वीकृत',
        'Redirecting to Dashboard': 'डैशबोर्ड पर भेजा जा रहा है',
        'Failed to load dashboard data.': 'डैशबोर्ड डेटा लोड नहीं हो सका।',
        'Failed to load profile data.': 'प्रोफाइल डेटा लोड नहीं हो सका।',
        'Dashboard data could not be loaded.': 'डैशबोर्ड डेटा लोड नहीं हो सका।',
        'Retry': 'फिर प्रयास करें',
        'Student Dashboard': 'स्टूडेंट डैशबोर्ड',
        'Welcome back': 'वापसी पर स्वागत है',
        'Student Name': 'छात्र का नाम',
        'Enrolled Account': 'पंजीकृत अकाउंट',
        'Roll Number': 'रोल नंबर',
        'Unique ID': 'यूनिक आईडी',
        'Class / Batch': 'कक्षा / बैच',
        'Assigned Cohort': 'असाइन बैच',
        'Average Score': 'औसत स्कोर',
        'Overall Performance': 'कुल प्रदर्शन',
        'Pending Fees': 'बकाया फीस',
        'Paid': 'भुगतान',
        'Attendance (MTD)': 'उपस्थिति (मासिक)',
        'Monthly Overview': 'मासिक अवलोकन',
        'Present': 'उपस्थित',
        'Absent': 'अनुपस्थित',
        'Late': 'देरी',
        'Total Sessions': 'कुल सेशन',
        'tracked': 'ट्रैक्ड',
        'pending tracking': 'ट्रैकिंग लंबित',
        'Tracked': 'ट्रैक्ड',
        'Not tracked': 'ट्रैक नहीं',
        'Recent Attendance': 'हाल की उपस्थिति',
        'Latest Sessions': 'नवीनतम सेशन',
        'records': 'रिकॉर्ड',
        'No recent attendance records yet.': 'अभी तक हाल की उपस्थिति रिकॉर्ड उपलब्ध नहीं हैं।',
        'View full attendance': 'पूरी उपस्थिति देखें',
        'Profile data could not be loaded.': 'प्रोफाइल डेटा लोड नहीं हो सका।',
        'Loading Profile...': 'प्रोफाइल लोड हो रही है...',
        'Enabled': 'चालू',
        'App Only': 'केवल ऐप',
        'Disabled': 'बंद',
        'Not Enabled': 'चालू नहीं',
        'Enrollment': 'नामांकन',
        'Class / Level': 'कक्षा / स्तर',
        'Not Assigned': 'असाइन नहीं',
        'Active Batch': 'सक्रिय बैच',
        'Admission': 'प्रवेश',
        'Personal Details': 'व्यक्तिगत विवरण',
        'Date of Birth': 'जन्म तिथि',
        'Gender': 'लिंग',
        'Contact': 'संपर्क',
        'Email': 'ईमेल',
        'Address': 'पता',
        'Parents / Guardians': 'माता-पिता / अभिभावक',
        'Father Name': 'पिता का नाम',
        'Mother Name': 'माता का नाम',
        'Guardian Contact': 'अभिभावक संपर्क',
        'Attendance Stats': 'उपस्थिति आँकड़े',
        'Overall Present': 'कुल उपस्थिति',
        'out of': 'में से',
        'days': 'दिन',
        'Recent Records': 'हाल के रिकॉर्ड',
        'Security': 'सुरक्षा',
        'New passwords do not match.': 'नए पासवर्ड मेल नहीं खाते।',
        'Password updated successfully.': 'पासवर्ड सफलतापूर्वक अपडेट हो गया।',
        'Failed to reset password.': 'पासवर्ड रीसेट नहीं हो सका।',
        'Current Password': 'वर्तमान पासवर्ड',
        'Enter current password': 'वर्तमान पासवर्ड दर्ज करें',
        'New Password': 'नया पासवर्ड',
        'Enter new password': 'नया पासवर्ड दर्ज करें',
        'Confirm Password': 'पासवर्ड की पुष्टि करें',
        'Confirm new password': 'नया पासवर्ड फिर दर्ज करें',
        'Validating...': 'जांच हो रही है...',
        'Update Password': 'पासवर्ड अपडेट करें',
        'Notifications': 'नोटिफिकेशन',
        'Push Notifications': 'पुश नोटिफिकेशन',
        'Enable alerts on this phone for announcements and updates.': 'घोषणाओं और अपडेट के लिए इस फोन पर अलर्ट चालू करें।',
        'Notifications enabled for this device.': 'इस डिवाइस के लिए नोटिफिकेशन चालू हो गए हैं।',
        'Unable to enable notifications right now.': 'अभी नोटिफिकेशन चालू नहीं हो सके।',
        'Enabling...': 'चालू किया जा रहा है...',
        'Refresh Notification Setup': 'नोटिफिकेशन सेटअप रीफ्रेश करें',
        'Enable Notifications': 'नोटिफिकेशन चालू करें',
        'Assigned Batch': 'असाइन बैच',
        'Batch': 'बैच',
        'Classroom': 'कक्षा कक्ष',
        'Course Type': 'कोर्स प्रकार',
        'Academic': 'अकादमिक',
        'Batch Subjects': 'बैच विषय',
        'No subjects assigned': 'कोई विषय असाइन नहीं है',
        'Close': 'बंद करें',
        'This build is trying to reach {{url}}. If you are using the local backend, keep it running and connect the phone to the same Wi-Fi.': 'यह बिल्ड {{url}} से कनेक्ट करने की कोशिश कर रहा है। यदि आप लोकल बैकएंड उपयोग कर रहे हैं, तो उसे चालू रखें और फोन को उसी Wi-Fi से कनेक्ट करें।',
        'Failed to load subjects.': 'विषय लोड नहीं हो सके।',
        'Academic Curriculum': 'शैक्षणिक पाठ्यक्रम',
        'Manage your enrolled subjects and Faculty.': 'अपने विषयों और विषय विशेषज्ञों को देखें और प्रबंधित करें।',
        'Search subjects or teachers...': 'विषय या शिक्षक खोजें...',
        'View your subject performance and results': 'अपने विषयवार प्रदर्शन और परिणाम देखें',
        'Active': 'सक्रिय',
        'Unassigned': 'असाइन नहीं',
        'Avg. Test Score': 'औसत टेस्ट स्कोर',
        'Subject Hub': 'विषय केंद्र',
        'No subjects found': 'कोई विषय नहीं मिला',
        'We couldn\'t find any subjects assigned to your batch. Please contact the administration if this is an error.': 'आपके बैच के लिए कोई विषय नहीं मिला। यदि यह त्रुटि है तो प्रशासन से संपर्क करें।',
        'Failed to load attendance data.': 'उपस्थिति डेटा लोड नहीं हो सका।',
        'Attendance data could not be loaded.': 'उपस्थिति डेटा लोड नहीं हो सका।',
        'Attendance Dashboard': 'उपस्थिति डैशबोर्ड',
        'Track your presence across all academic subjects.': 'सभी विषयों में अपनी उपस्थिति देखें और ट्रैक करें।',
        'Total Classes': 'कुल कक्षाएं',
        'Cumulative Sessions': 'कुल सेशन',
        'Classes Attended': 'उपस्थित कक्षाएं',
        'Sessions Present': 'उपस्थित सेशन',
        'Overall Percentage': 'कुल प्रतिशत',
        'Presence Rating': 'उपस्थिति रेटिंग',
        'Subject-wise Analytics': 'विषयवार विश्लेषण',
        'Attended': 'उपस्थित',
        'View Details': 'विवरण देखें',
        'No subject attendance data available yet.': 'अभी तक विषयवार उपस्थिति डेटा उपलब्ध नहीं है।',
        'Academic Requirement': 'शैक्षणिक आवश्यकता',
        'Students must maintain at least 75% attendance in each subject to be eligible for final examinations. For any disputes regarding your status, please visit the HOD office.': 'अंतिम परीक्षा के लिए पात्र होने हेतु प्रत्येक विषय में कम से कम 75% उपस्थिति जरूरी है। किसी भी विवाद के लिए HOD कार्यालय से संपर्क करें।',
        'Assessment': 'मूल्यांकन',
        'Score Obtained': 'प्राप्त अंक',
        'Detailed Assessment': 'विस्तृत मूल्यांकन',
        'Chapter': 'अध्याय',
        'Test Date': 'परीक्षा तिथि',
        'Pass / Excellent': 'उत्तीर्ण / उत्कृष्ट',
        'Needs Re-revision': 'दोबारा संशोधन आवश्यक',
        'Teacher\'s Remarks': 'शिक्षक की टिप्पणी',
        'No specific feedback provided for this assessment.': 'इस मूल्यांकन के लिए कोई विशेष प्रतिक्रिया उपलब्ध नहीं है।',
        'Close Details': 'विवरण बंद करें',
        'Failed to load results data. Please try again later.': 'परिणाम डेटा लोड नहीं हो सका। कृपया बाद में फिर प्रयास करें।',
        'Academic Analytics': 'शैक्षणिक विश्लेषण',
        'View your test scores, track progress, and identify areas for improvement.': 'अपने टेस्ट स्कोर देखें, प्रगति ट्रैक करें और सुधार के क्षेत्रों को पहचानें।',
        'Tests Attempted': 'दिए गए टेस्ट',
        'Warning Status': 'चेतावनी स्थिति',
        'Weak Subjects': 'कमजोर विषय',
        'On Track': 'सही प्रगति पर',
        'Progress Over Time': 'समय के साथ प्रगति',
        'More test data needed to chart progress.': 'प्रगति ग्राफ दिखाने के लिए और टेस्ट डेटा चाहिए।',
        'Priority Subject Focus': 'प्राथमिकता वाले विषय',
        'Click on a subject to review weak chapters and teacher\'s feedback.': 'कमजोर अध्याय और शिक्षक की प्रतिक्रिया देखने के लिए किसी विषय पर क्लिक करें।',
        'View Focus Audit': 'फोकस विश्लेषण देखें',
        'Complete Test History': 'पूरा टेस्ट इतिहास',
        'Search by test name or chapter...': 'टेस्ट नाम या अध्याय से खोजें...',
        'All Statuses': 'सभी स्थितियां',
        'Passed': 'उत्तीर्ण',
        'Needs Work': 'अधिक अभ्यास आवश्यक',
        'Newest First': 'नवीनतम पहले',
        'Oldest First': 'पुराने पहले',
        'No results match your criteria.': 'आपके चयन के अनुसार कोई परिणाम नहीं मिला।',
        'Remark:': 'टिप्पणी:',
        'Loading more...': 'और लोड हो रहा है...',
        'Load more results': 'और परिणाम लोड करें',
        'Failed to load leaderboard context.': 'लीडरबोर्ड संदर्भ लोड नहीं हो सका।',
        'Failed to load rankings.': 'रैंकिंग लोड नहीं हो सकी।',
        'Top Academic Performers': 'शीर्ष शैक्षणिक प्रदर्शनकर्ता',
        'My Batch': 'मेरा बैच',
        'Global': 'ग्लोबल',
        'Filter by Subject': 'विषय के अनुसार फ़िल्टर करें',
        'All Subjects': 'सभी विषय',
        'Updating Ranks...': 'रैंक अपडेट हो रही है...',
        'No ranking data available yet.': 'अभी तक रैंकिंग डेटा उपलब्ध नहीं है।',
        'Tests': 'टेस्ट',
        'Loading fee details...': 'फीस विवरण लोड हो रहा है...',
        'Pending Dues': 'बकाया राशि',
        'Total Paid': 'कुल भुगतान',
        'Fee History': 'फीस इतिहास',
        'No Fee Records Found': 'कोई फीस रिकॉर्ड नहीं मिला',
        'It looks like you don\'t have any generated bills yet. Please wait for the admin to initiate a billing cycle.': 'लगता है अभी तक आपके लिए कोई बिल तैयार नहीं हुआ है। कृपया एडमिन द्वारा बिलिंग शुरू होने तक प्रतीक्षा करें।',
        'Status:': 'स्थिति:',
        'Total Billed': 'कुल बिल',
        'Bill Breakdown': 'बिल विवरण',
        'Monthly Tuition': 'मासिक ट्यूशन फीस',
        'Late Fine Penalty': 'देर से भुगतान जुर्माना',
        'Net Payable': 'देय कुल राशि',
        'Download Receipt': 'रसीद डाउनलोड करें',
        'Remaining Due': 'शेष बकाया',
        'No payments made yet towards this billing cycle.': 'इस बिलिंग अवधि के लिए अभी तक कोई भुगतान नहीं किया गया है।',
        'Fee Receipt': 'फीस रसीद',
        'Student fee receipt PDF': 'छात्र फीस रसीद PDF',
        'Unable to save receipt on this device.': 'इस डिवाइस पर रसीद सेव नहीं की जा सकी।',
        'Error generating receipt': 'रसीद बनाने में त्रुटि हुई',
        'Failed to load subject analytics.': 'विषय विश्लेषण लोड नहीं हो सका।',
        'Loading {{subject}} analytics...': '{{subject}} का विश्लेषण लोड हो रहा है...',
        'Back to Performance Dashboard': 'प्रदर्शन डैशबोर्ड पर वापस जाएं',
        'Loading Batch...': 'बैच लोड हो रहा है...',
        'Total Assessments': 'कुल मूल्यांकन',
        'Faculty': 'विषय विशेषज्ञ',
        'Weak Chapters': 'कमजोर अध्याय',
        'High priority areas requiring revision.': 'ये उच्च प्राथमिकता वाले क्षेत्र हैं जिनमें पुनरावृत्ति जरूरी है।',
        'No Weak Chapters!': 'कोई कमजोर अध्याय नहीं!',
        'Excellent performance maintained.': 'उत्कृष्ट प्रदर्शन बनाए रखा गया है।',
        'REMARK:': 'टिप्पणी:',
        'Subject Testimony': 'विषय इतिहास',
        'No assessment history for this subject.': 'इस विषय के लिए कोई मूल्यांकन इतिहास उपलब्ध नहीं है।',
        'Qualified': 'योग्य',
        'Needs Revision': 'पुनरावृत्ति आवश्यक',
        'Feedback': 'फीडबैक',
        'Performance': 'प्रदर्शन',
        'Payment History': 'भुगतान इतिहास'
        ,
        'Receipt Preview': 'रसीद पूर्वावलोकन',
        'Download': 'डाउनलोड',
        'Generating PDF...': 'PDF तैयार हो रही है...',
        'Ready to Save': 'सेव करने के लिए तैयार',
        'PDF preview is limited on mobile device. Please save the receipt to view it.': 'मोबाइल डिवाइस पर PDF प्रीव्यू सीमित है। देखने के लिए रसीद सेव करें।',
        'Save Receipt': 'रसीद सेव करें',
        'Analysis': 'विश्लेषण',
        'Fee Details': 'फीस विवरण',
        'ID': 'आईडी',
        'Parent Details': 'अभिभावक विवरण',
        'Payment Breakdown': 'भुगतान विवरण',
        'Item Description': 'विवरण',
        'Amount': 'राशि',
        'Tuition Fee': 'ट्यूशन फीस',
        'Registration Fee': 'प्रवेश शुल्क',
        'Late Fine': 'विलंब शुल्क',
        'Gross Charges': 'कुल शुल्क',
        'Discount Applied': 'लागू छूट',
        'You Saved': 'आपने बचत की',
        'Total Payable': 'कुल देय',
        'Net Balance': 'कुल बकाया',
        'Full Paid Receipt': 'पूर्ण भुगतान रसीद',
        'Info': 'जानकारी',
        'Syllabus': 'सिलेबस',
        'Subject Detail': 'विषय विवरण',
        'Track results, attendance, and faculty updates in one place.': 'एक ही जगह पर परिणाम, उपस्थिति और शिक्षक अपडेट देखें।',
        'Attendance Overview': 'उपस्थिति अवलोकन',
        'No Syllabus Data': 'सिलेबस डेटा उपलब्ध नहीं है',
        'The syllabus for this subject has not been added yet. Please check back later.': 'इस विषय का सिलेबस अभी जोड़ा नहीं गया है। कृपया बाद में फिर जांचें।',
        'Chapter Tracking Dashboard': 'अध्याय ट्रैकिंग डैशबोर्ड',
        'Analytics': 'विश्लेषण',
        'Total Chapters': 'कुल अध्याय',
        'Completed Chapters': 'पूर्ण अध्याय',
        'Remaining Chapters': 'शेष अध्याय',
        'Next Chapter ETA': 'अगले अध्याय का अनुमान',
        'Completion Analytics': 'पूर्णता विश्लेषण',
        'of': 'में से',
        'chapters completed': 'अध्याय पूरे हुए',
        'Progress Alert': 'प्रगति अलर्ट',
        'Entire syllabus has been covered. Great consistency!': 'पूरा सिलेबस कवर हो चुका है। शानदार निरंतरता!',
        'Next focus': 'अगला फोकस',
        'Estimated completion': 'अनुमानित पूर्णता',
        'chapters remaining': 'अध्याय शेष',
        'Keep your pace steady to improve completion analytics.': 'पूर्णता विश्लेषण बेहतर करने के लिए अपनी गति स्थिर रखें।',
        'Upcoming Chapters': 'आगामी अध्याय',
        'Chapter list is not available yet, but overall chapter targets are active for this subject.': 'अभी अध्याय सूची उपलब्ध नहीं है, लेकिन इस विषय के कुल अध्याय लक्ष्य सक्रिय हैं।',
        'Ongoing': 'जारी',
        'Upcoming': 'आगामी',
        'Completed': 'पूर्ण',
        'Done': 'पूर्ण',
        'All': 'सभी',
        'Scheduled': 'निर्धारित',
        'Upcoming Schedule': 'आगामी समय-सारणी',
        'These are scheduled tests. Scores and percentages will appear after results are declared.': 'ये निर्धारित टेस्ट हैं। परिणाम घोषित होने के बाद अंक और प्रतिशत दिखाई देंगे।',
        'Scheduled on': 'निर्धारित तिथि',
        'Result Pending': 'परिणाम लंबित',
        'Failed': 'अनुत्तीर्ण',
        'No Upcoming Tests': 'कोई आगामी टेस्ट नहीं',
        'No Completed Tests': 'कोई पूर्ण टेस्ट नहीं',
        'No Scheduled Tests': 'कोई निर्धारित टेस्ट नहीं',
        'No Declared Results': 'कोई घोषित परिणाम नहीं',
        'Upcoming tests will appear here once they are scheduled.': 'जैसे ही टेस्ट निर्धारित होंगे, वे यहां दिखाई देंगे।',
        'Completed tests will appear here once the exam cycle finishes.': 'जैसे ही परीक्षा चक्र पूरा होगा, पूर्ण टेस्ट यहां दिखाई देंगे।',
        'Declared exam results will appear here once published by faculty.': 'शिक्षक द्वारा प्रकाशित होने पर घोषित परीक्षा परिणाम यहां दिखाई देंगे।',
        'Lead Faculty': 'मुख्य शिक्षक',
        'Subject Code': 'विषय कोड',
        'Detailed Logs': 'विस्तृत रिकॉर्ड',
        'Scheduled Test': 'निर्धारित टेस्ट',
        'Result not declared yet for this test.': 'इस टेस्ट का परिणाम अभी घोषित नहीं हुआ है।',
        'Scores and percentage will be visible after evaluation is completed.': 'मूल्यांकन पूरा होने के बाद अंक और प्रतिशत दिखाई देंगे।',
        'Score': 'अंक',
        'Percentage': 'प्रतिशत',
        'Date': 'तिथि',
        'Status': 'स्थिति',
        'Test': 'परीक्षा'
    }
};

const LanguageContext = createContext(null);

const safeString = (val) => {
    if (val === null || val === undefined) return '';
    try {
        if (typeof val === 'symbol') {
            return val.toString();
        }
        if (typeof val === 'object') {
            return '[Object]';
        }
        return String(val);
    } catch (e) {
        console.error('LanguageContext: Failed to stringify value:', e);
        return '[Error]';
    }
};

const interpolate = (template, values = {}) => {
    const templateStr = typeof template === 'string' ? template : safeString(template);
    
    return Object.entries(values).reduce(
        (result, [key, value]) => {
            return result.replaceAll(`{{${key}}}`, safeString(value));
        },
        templateStr
    );
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en');

    useEffect(() => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
        document.documentElement.lang = language === 'hi' ? 'hi' : 'en';
    }, [language]);

    const value = useMemo(() => ({
        language,
        setLanguage,
        toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'hi' : 'en')),
        t: (key, values = {}) => {
            const template = language === 'hi'
                ? translations.hi[key] || key
                : key;
            return interpolate(template, values);
        }
    }), [language]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used inside LanguageProvider');
    }
    return context;
};
